spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root
    password: pal-training

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointUrl:  http://192.168.136.249:9000
  accessKey: 11DL9TXTRZLH5IJ6X067
  secretKey: JdbL3C68SKz0FWEwveICs4Q+teNOWLI/WylGLc8d
  bucketName: moviefun
